version: "2"
services:
  fullstacktesting-frontend:
    build: .
    depends_on:
      - selenium
    ports:
      - "8000:8000"
  selenium:
    image: elgalu/selenium
    network_mode: host
    environment:
      - SELENIUM_HUB_PORT=4444
  mock:
    image: elgalu/google_adwords_mock
    network_mode: host
    tty: true
    environment:
      - MOCK_SERVER_PORT=8080
